# Generated by Django 3.2.15 on 2022-08-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='PostAd',
            name='nct',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='PostAd',
            name='tax',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='PostAd',
            name='year',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
