# Generated by Django 3.2.15 on 2022-09-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='postad',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
