# Generated by Django 3.2.15 on 2022-09-15 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220915_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.postad'),
        ),
    ]
