# Generated by Django 3.2.15 on 2022-08-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220828_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postad',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='postad',
            name='likes',
        ),
        migrations.AddField(
            model_name='postad',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='postad',
            name='nct',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='postad',
            name='tax',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='postad',
            name='year',
            field=models.DateField(),
        ),
    ]
