# Generated by Django 3.2.15 on 2022-09-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220831_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercomment',
            old_name='PostAd',
            new_name='post',
        ),
    ]
