# Generated by Django 3.2.15 on 2022-09-22 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('about_me', models.CharField(max_length=500)),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_name', to='blog.postad')),
                ('last_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.postad')),
            ],
        ),
    ]
