# Generated by Django 3.2.15 on 2022-09-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20220926_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/shahid129/image/upload/v1664148089/media/girl_aytby8.jpg', null=True, upload_to=''),
        ),
    ]
